name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Check code formatting
      id: format
      continue-on-error: true
      run: uv run ruff format --check .

    - name: Check code linting
      id: lint
      continue-on-error: true
      run: uv run ruff check .

    - name: Check import sorting
      id: imports
      continue-on-error: true
      run: uv run ruff check --select I --diff .

    - name: Type check with mypy
      id: typecheck
      continue-on-error: true
      run: uv run mypy main.py

    - name: Lint shell scripts with shellcheck
      id: shellcheck
      continue-on-error: true
      run: shellcheck poor* lib/*.sh templates/*.sh

    - name: Check results
      if: steps.format.outcome == 'failure' || steps.lint.outcome == 'failure' || steps.imports.outcome == 'failure' || steps.typecheck.outcome == 'failure' || steps.shellcheck.outcome == 'failure'
      run: |
        echo "❌ Some linting checks failed:"
        echo "- Format check: ${{ steps.format.outcome }}"
        echo "- Lint check: ${{ steps.lint.outcome }}"
        echo "- Import sorting: ${{ steps.imports.outcome }}"
        echo "- Type checking: ${{ steps.typecheck.outcome }}"
        echo "- Shell checking: ${{ steps.shellcheck.outcome }}"
        exit 1

  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint Dockerfile with hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Test with pytest
      run: uv run pytest tests/ -v
