name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Lint and format with Ruff
      uses: astral-sh/ruff-action@v1
      with:
        src: "./poor_installer_web"
        args: "check --output-format=github"

    - name: Check code formatting with Ruff
      uses: astral-sh/ruff-action@v1
      with:
        src: "./poor_installer_web"
        args: "format --check"

    - name: Type check with mypy
      run: uv run mypy poor_installer_web/*.py

    - name: Lint shell scripts with shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './lib ./templates'
        additional_files: 'poorcolumn poorcurl poorcurl-openssl poor-installer poornmap poorsocat'
        severity: error

  hadolint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint Dockerfile with hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Test with pytest
      run: uv run pytest tests/ -v
